apiVersion: v1
kind: Pod
metadata:
  name: stress-pod
spec:
  containers:
    - name: stress
      image: busybox
      command: ["sh", "-c", "while true; do dd if=/dev/zero of=/dev/null; done"]
      resources:
        limits:
          cpu: "1"
          memory: "256Mi"
        requests:
          cpu: "0.5"
          memory: "128Mi"
